# Generated by Django 4.2.17 on 2025-01-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('rank', models.CharField(blank=True, max_length=100, null=True)),
                ('raiting', models.CharField(blank=True, max_length=100, null=True)),
                ('tournaments', models.CharField(blank=True, max_length=100, null=True)),
                ('games', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'игрок',
                'verbose_name_plural': 'игроки',
            },
        ),
    ]
